//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCAN_Client.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NULL")]
        public string XmlOrTempPath {
            get {
                return ((string)(this["XmlOrTempPath"]));
            }
            set {
                this["XmlOrTempPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NULL")]
        public string S19Path {
            get {
                return ((string)(this["S19Path"]));
            }
            set {
                this["S19Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SoftwareVersion {
            get {
                return ((string)(this["SoftwareVersion"]));
            }
            set {
                this["SoftwareVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HardwareVersion {
            get {
                return ((string)(this["HardwareVersion"]));
            }
            set {
                this["HardwareVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PCAN")]
        public string selectDevice {
            get {
                return ((string)(this["selectDevice"]));
            }
            set {
                this["selectDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NULL")]
        public string customInstruction {
            get {
                return ((string)(this["customInstruction"]));
            }
            set {
                this["customInstruction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FlashDriverSelectIndex {
            get {
                return ((int)(this["FlashDriverSelectIndex"]));
            }
            set {
                this["FlashDriverSelectIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1968")]
        public int UDS_TX_ID {
            get {
                return ((int)(this["UDS_TX_ID"]));
            }
            set {
                this["UDS_TX_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1976")]
        public int UDS_RX_ID {
            get {
                return ((int)(this["UDS_RX_ID"]));
            }
            set {
                this["UDS_RX_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ProjectSelectIndex {
            get {
                return ((int)(this["ProjectSelectIndex"]));
            }
            set {
                this["ProjectSelectIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CAN")]
        public string CANType {
            get {
                return ((string)(this["CANType"]));
            }
            set {
                this["CANType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public string Delayus {
            get {
                return ((string)(this["Delayus"]));
            }
            set {
                this["Delayus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("自动加载")]
        public string JsonSelect {
            get {
                return ((string)(this["JsonSelect"]));
            }
            set {
                this["JsonSelect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("USB_1")]
        public string PCAN_Channel {
            get {
                return ((string)(this["PCAN_Channel"]));
            }
            set {
                this["PCAN_Channel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Channel 3")]
        public string CANoe_Channel {
            get {
                return ((string)(this["CANoe_Channel"]));
            }
            set {
                this["CANoe_Channel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SetDLCSelectIndex {
            get {
                return ((int)(this["SetDLCSelectIndex"]));
            }
            set {
                this["SetDLCSelectIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("27款")]
        public string Service2FProjectSelect {
            get {
                return ((string)(this["Service2FProjectSelect"]));
            }
            set {
                this["Service2FProjectSelect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string TestRx0_Save {
            get {
                return ((string)(this["TestRx0_Save"]));
            }
            set {
                this["TestRx0_Save"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string TestRx1_Save {
            get {
                return ((string)(this["TestRx1_Save"]));
            }
            set {
                this["TestRx1_Save"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string TestRx2_Save {
            get {
                return ((string)(this["TestRx2_Save"]));
            }
            set {
                this["TestRx2_Save"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string TestRx3_Save {
            get {
                return ((string)(this["TestRx3_Save"]));
            }
            set {
                this["TestRx3_Save"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string TestRx4_Save {
            get {
                return ((string)(this["TestRx4_Save"]));
            }
            set {
                this["TestRx4_Save"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string TestRx5_Save {
            get {
                return ((string)(this["TestRx5_Save"]));
            }
            set {
                this["TestRx5_Save"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string TestRx6_Save {
            get {
                return ((string)(this["TestRx6_Save"]));
            }
            set {
                this["TestRx6_Save"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string TestRx7_Save {
            get {
                return ((string)(this["TestRx7_Save"]));
            }
            set {
                this["TestRx7_Save"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string DBCFilePath {
            get {
                return ((string)(this["DBCFilePath"]));
            }
            set {
                this["DBCFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ASC")]
        public string SaveFileType {
            get {
                return ((string)(this["SaveFileType"]));
            }
            set {
                this["SaveFileType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NULL")]
        public string ChartShowSave {
            get {
                return ((string)(this["ChartShowSave"]));
            }
            set {
                this["ChartShowSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int ChartShowDataTimeDelayTime {
            get {
                return ((int)(this["ChartShowDataTimeDelayTime"]));
            }
            set {
                this["ChartShowDataTimeDelayTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int ChartShowDataNum {
            get {
                return ((int)(this["ChartShowDataNum"]));
            }
            set {
                this["ChartShowDataNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int comboBoxExcelSaveTimeSelectIndex {
            get {
                return ((int)(this["comboBoxExcelSaveTimeSelectIndex"]));
            }
            set {
                this["comboBoxExcelSaveTimeSelectIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxSaveExcelChecked {
            get {
                return ((bool)(this["checkBoxSaveExcelChecked"]));
            }
            set {
                this["checkBoxSaveExcelChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxSaveAscChecked {
            get {
                return ((bool)(this["checkBoxSaveAscChecked"]));
            }
            set {
                this["checkBoxSaveAscChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NULL")]
        public string SetSwVer {
            get {
                return ((string)(this["SetSwVer"]));
            }
            set {
                this["SetSwVer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NULL")]
        public string SetHwVer {
            get {
                return ((string)(this["SetHwVer"]));
            }
            set {
                this["SetHwVer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NULL")]
        public string SetPartVer {
            get {
                return ((string)(this["SetPartVer"]));
            }
            set {
                this["SetPartVer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LP_24YearSelected {
            get {
                return ((bool)(this["LP_24YearSelected"]));
            }
            set {
                this["LP_24YearSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int StreamingThresholdMB {
            get {
                return ((int)(this["StreamingThresholdMB"]));
            }
            set {
                this["StreamingThresholdMB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ChartChannelFilter {
            get {
                return ((string)(this["ChartChannelFilter"]));
            }
            set {
                this["ChartChannelFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LogFilePaths {
            get {
                return ((string)(this["LogFilePaths"]));
            }
            set {
                this["LogFilePaths"] = value;
            }
        }
    }
}
